version: '2'
services:
  app:
    build: .
    ports:
     - "8082:8082"
    links:
      - "db:redis"
  db:
    image: "redis:latest"
    hostname: redis
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - "6379:6379"
